import { Page } from 'playwright';
import { z } from 'zod';
import { BrowserManager } from './manager.js';
import { ObservationTarget } from './registry.js';
export const FailureTypeSchema = z.enum(['target_found', 'target_unusable', 'locator_not_found', 'navigation_failure', 'page_load_failure', 'authentication_failure']);
export const CandidateEvidenceSchema = z.object({ selector: z.string(), tagName: z.string().optional(), role: z.string().optional(), text: z.string().optional(), ariaLabel: z.string().optional(), id: z.string().optional(), href: z.string().optional(), type: z.string().optional(), visible: z.boolean(), enabled: z.boolean().optional(), boundingBox: z.object({ x: z.number(), y: z.number(), width: z.number(), height: z.number() }).nullable().optional(), index: z.number().int().nonnegative().optional(), deterministicScore: z.number().min(0).max(1).optional() });
export type CandidateEvidence = z.infer<typeof CandidateEvidenceSchema>;
export const PageEvidenceSchema = z.object({ route: z.string(), url: z.string(), title: z.string().optional(), targetId: z.string(), target: z.object({ id: z.string(), route: z.string(), selector: z.string(), description: z.string().optional() }), originalTarget: z.object({ selector: z.string(), expectedRole: z.string().optional(), expectedId: z.string().optional(), expectedText: z.string().optional(), expectedAriaLabel: z.string().optional() }), elementFound: z.boolean(), element: z.object({ tagName: z.string().optional(), id: z.string().optional(), role: z.string().optional(), text: z.string().optional(), ariaLabel: z.string().optional(), href: z.string().optional(), type: z.string().optional(), visible: z.boolean(), enabled: z.boolean().optional(), boundingBox: z.object({ x: z.number(), y: z.number(), width: z.number(), height: z.number() }).nullable().optional() }).optional(), candidates: z.array(CandidateEvidenceSchema), failureType: FailureTypeSchema, timestamp: z.string() });
export type PageEvidence = z.infer<typeof PageEvidenceSchema>;
const clean = (value: string | null) => { const text = value?.replace(/\s+/g, ' ').trim(); return text || undefined; };
const cssString = (value: string) => value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\a ').replace(/\r/g, '\\d ');
const selectorFor = (tag: string, id?: string, aria?: string) => id ? `[id="${cssString(id)}"]` : aria ? `[aria-label="${cssString(aria)}"]` : tag;
async function readElement(locator: ReturnType<Page['locator']>) { const tagName = await locator.evaluate((node) => node.tagName.toLowerCase()); const id = await locator.getAttribute('id'); const role = await locator.getAttribute('role'); const ariaLabel = await locator.getAttribute('aria-label'); const text = clean(await locator.textContent()); const href = await locator.getAttribute('href'); const type = await locator.getAttribute('type'); const visible = await locator.isVisible(); const enabled = await locator.isEnabled().catch(() => undefined); const boundingBox = await locator.boundingBox(); return { tagName, id: id || undefined, role: role || undefined, text, ariaLabel: ariaLabel || undefined, href: href || undefined, type: type || undefined, visible, enabled, boundingBox }; }
export async function observeTarget(manager: BrowserManager, target: ObservationTarget): Promise<PageEvidence> {
  const timestamp = new Date().toISOString(); let page: Page | undefined;
  try { page = await manager.createPage(); const status = await manager.navigate(page, target.route); if (status >= 400) throw new Error(`Page load failed with HTTP ${status}`); } catch (error) { await page?.close().catch(() => undefined); const message = error instanceof Error ? error.message : 'Navigation failed'; const failureType = /401|403|login/i.test(message) ? 'authentication_failure' : /page load failed/i.test(message) ? 'page_load_failure' : 'navigation_failure'; return PageEvidenceSchema.parse({ route: target.route, url: manager.url(target.route), targetId: target.id, target, originalTarget: { selector: target.selector }, elementFound: false, candidates: [], failureType, timestamp }); }
  try { return await observePage(page, target); } finally { await page.close(); }
}

export async function observePage(page: Page, target: ObservationTarget): Promise<PageEvidence> {
  const locator = page.locator(target.selector).first(); const count = await page.locator(target.selector).count(); const candidates: z.infer<typeof CandidateEvidenceSchema>[] = []; const all = page.locator('button, a, input, [role], [aria-label], [id]'); const limit = Math.min(await all.count(), 100);
  for (let i = 0; i < limit; i++) { const data = await readElement(all.nth(i)); const selector = selectorFor(data.tagName, data.id, data.ariaLabel); if (!candidates.some((item) => item.selector === selector)) candidates.push({ selector, tagName: data.tagName, role: data.role, text: data.text, ariaLabel: data.ariaLabel, id: data.id, href: data.href, type: data.type, visible: data.visible, enabled: data.enabled, boundingBox: data.boundingBox }); }
  const found = count > 0; const response = await page.evaluate(() => ({ url: location.href, title: document.title })); const targetSpec = target as ObservationTarget & { repair?: { expectedRole?: string; expectedId?: string; expectedText?: string; expectedAriaLabel?: string } };
  const element = found ? await readElement(locator) : undefined;
  const failureType = /\/login\/?$/.test(new URL(response.url).pathname) ? 'authentication_failure' : !found ? 'locator_not_found' : !element?.visible || element.enabled === false ? 'target_unusable' : 'target_found';
  return PageEvidenceSchema.parse({ route: target.route, url: response.url, title: response.title, targetId: target.id, target, originalTarget: { selector: target.selector, expectedRole: targetSpec.repair?.expectedRole, expectedId: targetSpec.repair?.expectedId, expectedText: targetSpec.repair?.expectedText, expectedAriaLabel: targetSpec.repair?.expectedAriaLabel }, elementFound: found, element, candidates, failureType, timestamp: new Date().toISOString() });
}
